// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBRTy_DvG3LEdGshL8QI0NDlsbHpcXzmM',
    appId: '1:381585323049:web:c4b4427d0565b5f79ad838',
    messagingSenderId: '381585323049',
    projectId: 'plantin-test-task',
    authDomain: 'plantin-test-task.firebaseapp.com',
    storageBucket: 'plantin-test-task.firebasestorage.app',
    measurementId: 'G-FSH6GVJNMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXzamdc9Oi2UT-KEWgC-l7Oh5Q3qZ2DJ0',
    appId: '1:381585323049:android:7605998d0cf713359ad838',
    messagingSenderId: '381585323049',
    projectId: 'plantin-test-task',
    storageBucket: 'plantin-test-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7TtFKc2cV4Vv61sbYjex7lE1ibo14NDM',
    appId: '1:381585323049:ios:3bfdf3e52090af369ad838',
    messagingSenderId: '381585323049',
    projectId: 'plantin-test-task',
    storageBucket: 'plantin-test-task.firebasestorage.app',
    iosBundleId: 'com.example.plantinTestTask',
  );
}
